//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkDownEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkDownEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Accent.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add custom css files.
        /// </summary>
        public static string AddCustomCSS {
            get {
                return ResourceManager.GetString("AddCustomCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bold (Ctrl+B).
        /// </summary>
        public static string BoldCommand {
            get {
                return ResourceManager.GetString("BoldCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Check for update.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Code (Ctrl+K).
        /// </summary>
        public static string CodeCommand {
            get {
                return ResourceManager.GetString("CodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Col.
        /// </summary>
        public static string Col {
            get {
                return ResourceManager.GetString("Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please copy your custom css file into the following folder. It&apos;ll take effect after restart..
        /// </summary>
        public static string CopyCSS {
            get {
                return ResourceManager.GetString("CopyCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Current Version.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Date Stamp (Ctrl++Shift+D).
        /// </summary>
        public static string DateStampCommand {
            get {
                return ResourceManager.GetString("DateStampCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Don&apos;t remind for this update!.
        /// </summary>
        public static string DoNotRemindForThisUpdate {
            get {
                return ResourceManager.GetString("DoNotRemindForThisUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Don&apos;t save.
        /// </summary>
        public static string DoNotSave {
            get {
                return ResourceManager.GetString("DoNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Download Now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bold Text Area.
        /// </summary>
        public static string EmptyBoldAreaText {
            get {
                return ResourceManager.GetString("EmptyBoldAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Code.
        /// </summary>
        public static string EmptyCode {
            get {
                return ResourceManager.GetString("EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Description of the link.
        /// </summary>
        public static string EmptyHyperlinkDescription {
            get {
                return ResourceManager.GetString("EmptyHyperlinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Description of the image.
        /// </summary>
        public static string EmptyImageDescription {
            get {
                return ResourceManager.GetString("EmptyImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Italic Text Area.
        /// </summary>
        public static string EmptyItalicAreaText {
            get {
                return ResourceManager.GetString("EmptyItalicAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Title.
        /// </summary>
        public static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Environment.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný can&apos;t be exported in this version!.
        /// </summary>
        public static string Error_ExportError {
            get {
                return ResourceManager.GetString("Error_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exporting.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Export To.
        /// </summary>
        public static string ExportTo {
            get {
                return ResourceManager.GetString("ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to export.
        /// </summary>
        public static string FailedToExport {
            get {
                return ResourceManager.GetString("FailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Find Next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Find Previous.
        /// </summary>
        public static string FindPrevious {
            get {
                return ResourceManager.GetString("FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Find &amp; Replace.
        /// </summary>
        public static string FindReplace {
            get {
                return ResourceManager.GetString("FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Font Family.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Highlight Current Line.
        /// </summary>
        public static string HighlightCurrentLine {
            get {
                return ResourceManager.GetString("HighlightCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Horizontal Rule (Ctrl+R).
        /// </summary>
        public static string HorizontalRuleCommand {
            get {
                return ResourceManager.GetString("HorizontalRuleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hyperlink.
        /// </summary>
        public static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hyperlink (Ctrl+L).
        /// </summary>
        public static string HyperlinkCommand {
            get {
                return ResourceManager.GetString("HyperlinkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Image (Ctrl+G).
        /// </summary>
        public static string ImageCommand {
            get {
                return ResourceManager.GetString("ImageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Images|*.bmp;*.jpg;*.gif;*.png;*.tif.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The size of file is larger than 10MB, unable to upload!.
        /// </summary>
        public static string ImageSizeError {
            get {
                return ResourceManager.GetString("ImageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please input an image URL.
        /// </summary>
        public static string InputImage {
            get {
                return ResourceManager.GetString("InputImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please input an URL.
        /// </summary>
        public static string InputLink {
            get {
                return ResourceManager.GetString("InputLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert local image URL.
        /// </summary>
        public static string InsertLocalImage {
            get {
                return ResourceManager.GetString("InsertLocalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný International Settings.
        /// </summary>
        public static string InternationalSettings {
            get {
                return ResourceManager.GetString("InternationalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Italic (Ctrl+I).
        /// </summary>
        public static string ItalicCommand {
            get {
                return ResourceManager.GetString("ItalicCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Language will be switched after restart.
        /// </summary>
        public static string LanguageSwitch {
            get {
                return ResourceManager.GetString("LanguageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný List Item.
        /// </summary>
        public static string ListItem {
            get {
                return ResourceManager.GetString("ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ln.
        /// </summary>
        public static string Ln {
            get {
                return ResourceManager.GetString("Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Markdown Documents|*.md;*.markdown|All Files|*.*.
        /// </summary>
        public static string MarkDownFileFilter {
            get {
                return ResourceManager.GetString("MarkDownFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Match Case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Match Whole Word.
        /// </summary>
        public static string MatchWholeWord {
            get {
                return ResourceManager.GetString("MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný More Options.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New (Ctrl+N).
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New Document Created.
        /// </summary>
        public static string NewDocumentCreated {
            get {
                return ResourceManager.GetString("NewDocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New version is released!.
        /// </summary>
        public static string NewVersionIsReleased {
            get {
                return ResourceManager.GetString("NewVersionIsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Night Mode.
        /// </summary>
        public static string NightMode {
            get {
                return ResourceManager.GetString("NightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No CSS.
        /// </summary>
        public static string NoCSS {
            get {
                return ResourceManager.GetString("NoCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Online Image Storage Service.
        /// </summary>
        public static string OISS {
            get {
                return ResourceManager.GetString("OISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Online Image.
        /// </summary>
        public static string OnlineImage {
            get {
                return ResourceManager.GetString("OnlineImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open In External Browser (F6).
        /// </summary>
        public static string Open_In_External_Browser {
            get {
                return ResourceManager.GetString("Open_In_External_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open (Ctrl+O).
        /// </summary>
        public static string OpenCommand {
            get {
                return ResourceManager.GetString("OpenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný opened successfully.
        /// </summary>
        public static string OpenedSuccessfully {
            get {
                return ResourceManager.GetString("OpenedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open file failed!.
        /// </summary>
        public static string OpenFileFailed {
            get {
                return ResourceManager.GetString("OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open Right Now.
        /// </summary>
        public static string OpenRightNow {
            get {
                return ResourceManager.GetString("OpenRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open This Folder.
        /// </summary>
        public static string OpenThisFolder {
            get {
                return ResourceManager.GetString("OpenThisFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Optional Title.
        /// </summary>
        public static string OptionalTitle {
            get {
                return ResourceManager.GetString("OptionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ordered List (Ctrl+Shift+O).
        /// </summary>
        public static string OrderedListCommand {
            get {
                return ResourceManager.GetString("OrderedListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný QiniuConf.
        /// </summary>
        public static string QiniuConf {
            get {
                return ResourceManager.GetString("QiniuConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný QiniuUserDomainName.
        /// </summary>
        public static string QiniuUserDomainName {
            get {
                return ResourceManager.GetString("QiniuUserDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný QiniuUserScope.
        /// </summary>
        public static string QiniuUserScope {
            get {
                return ResourceManager.GetString("QiniuUserScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Quote (Ctrl+Q).
        /// </summary>
        public static string QuoteCommand {
            get {
                return ResourceManager.GetString("QuoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reading Mode/Preview Mode.
        /// </summary>
        public static string Reading_Preview_Mode {
            get {
                return ResourceManager.GetString("Reading_Preview_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Refresh (F5).
        /// </summary>
        public static string RefreshCommand {
            get {
                return ResourceManager.GetString("RefreshCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Regular Expression.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Replace All.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Replace Completed!.
        /// </summary>
        public static string ReplaceCompleted {
            get {
                return ResourceManager.GetString("ReplaceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ruler.
        /// </summary>
        public static string Ruler {
            get {
                return ResourceManager.GetString("Ruler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ruler Position.
        /// </summary>
        public static string RulerPosition {
            get {
                return ResourceManager.GetString("RulerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save As (Ctrl+Shift+S).
        /// </summary>
        public static string SaveAsCommand {
            get {
                return ResourceManager.GetString("SaveAsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save (Ctrl+S).
        /// </summary>
        public static string SaveCommand {
            get {
                return ResourceManager.GetString("SaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný saved successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save file failed!.
        /// </summary>
        public static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Scrollbar Synchronization.
        /// </summary>
        public static string Scrollbar_Synchronization {
            get {
                return ResourceManager.GetString("Scrollbar_Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select Image Type.
        /// </summary>
        public static string SelectImageType {
            get {
                return ResourceManager.GetString("SelectImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show Column Ruler.
        /// </summary>
        public static string ShowColumnRuler {
            get {
                return ResourceManager.GetString("ShowColumnRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show End Of Line.
        /// </summary>
        public static string ShowEndOfLine {
            get {
                return ResourceManager.GetString("ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show Line Numbers.
        /// </summary>
        public static string ShowLineNumbers {
            get {
                return ResourceManager.GetString("ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show MathJax.
        /// </summary>
        public static string ShowMathJax {
            get {
                return ResourceManager.GetString("ShowMathJax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show Preview.
        /// </summary>
        public static string ShowPreview {
            get {
                return ResourceManager.GetString("ShowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show Spaces.
        /// </summary>
        public static string ShowSpaces {
            get {
                return ResourceManager.GetString("ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show Tabs.
        /// </summary>
        public static string ShowTabs {
            get {
                return ResourceManager.GetString("ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Source Code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Successfully Exported.
        /// </summary>
        public static string SuccessfullyExported {
            get {
                return ResourceManager.GetString("SuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Time Stamp (Ctrl+T).
        /// </summary>
        public static string TimeStampCommand {
            get {
                return ResourceManager.GetString("TimeStampCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Heading (Ctrl+H).
        /// </summary>
        public static string TitleCommand {
            get {
                return ResourceManager.GetString("TitleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Microsoft Word|*.docx.
        /// </summary>
        public static string TypeDocxFilter {
            get {
                return ResourceManager.GetString("TypeDocxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Microsoft Word 2007-2016 Document Format.
        /// </summary>
        public static string TypeDocxToolTip {
            get {
                return ResourceManager.GetString("TypeDocxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Electronic Publication|*.epub.
        /// </summary>
        public static string TypeEpubFilter {
            get {
                return ResourceManager.GetString("TypeEpubFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Electronic Publication Format.
        /// </summary>
        public static string TypeEpubToolTip {
            get {
                return ResourceManager.GetString("TypeEpubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný HTML Web Page|*.html.
        /// </summary>
        public static string TypeHtmlFilter {
            get {
                return ResourceManager.GetString("TypeHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný HyperText Markup Language.
        /// </summary>
        public static string TypeHtmlToolTip {
            get {
                return ResourceManager.GetString("TypeHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný JPEG|*.jpg|PNG|*.png.
        /// </summary>
        public static string TypeImageFilter {
            get {
                return ResourceManager.GetString("TypeImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Images.
        /// </summary>
        public static string TypeImageToolTip {
            get {
                return ResourceManager.GetString("TypeImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LATEX Document|*.tex.
        /// </summary>
        public static string TypeLatexFilter {
            get {
                return ResourceManager.GetString("TypeLatexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný We suggest to compile exported tex files using XeLatex command if CJK characters exist in document.
        /// </summary>
        public static string TypeLatexToolTip {
            get {
                return ResourceManager.GetString("TypeLatexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Portable Document Format|*.pdf.
        /// </summary>
        public static string TypePdfFilter {
            get {
                return ResourceManager.GetString("TypePdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Portable Document Format.
        /// </summary>
        public static string TypePdfToolTip {
            get {
                return ResourceManager.GetString("TypePdfToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Plain HTML Web Page|*.html.
        /// </summary>
        public static string TypePlainHtmlFilter {
            get {
                return ResourceManager.GetString("TypePlainHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný HyperText Markup Language without any css.
        /// </summary>
        public static string TypePlainHtmlToolTip {
            get {
                return ResourceManager.GetString("TypePlainHtmlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rich Text Format|*.rtf.
        /// </summary>
        public static string TypeRTFFilter {
            get {
                return ResourceManager.GetString("TypeRTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rich Text Format.
        /// </summary>
        public static string TypeRTFTip {
            get {
                return ResourceManager.GetString("TypeRTFTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unordered List (Ctrl+U).
        /// </summary>
        public static string UnorderedListCommand {
            get {
                return ResourceManager.GetString("UnorderedListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unsaved Changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Untitled.
        /// </summary>
        public static string UntitledTitle {
            get {
                return ResourceManager.GetString("UntitledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Fetch App update information failed!.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Update Info.
        /// </summary>
        public static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upload Images (Don&apos;t upload illegal images).
        /// </summary>
        public static string UploadImagesTitle {
            get {
                return ResourceManager.GetString("UploadImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upload Local Image To Imgur（Outside PRC）.
        /// </summary>
        public static string UploadLocalImage2IMGUR {
            get {
                return ResourceManager.GetString("UploadLocalImage2IMGUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upload Local Image To Qiniu（PRC）.
        /// </summary>
        public static string UploadLocalImage2Qiniu {
            get {
                return ResourceManager.GetString("UploadLocalImage2Qiniu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upload Image To .
        /// </summary>
        public static string UploadToImageStorageService {
            get {
                return ResourceManager.GetString("UploadToImageStorageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Would you want to save your changes?.
        /// </summary>
        public static string WhetherSaveChanges {
            get {
                return ResourceManager.GetString("WhetherSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Wildcards.
        /// </summary>
        public static string Wildcards {
            get {
                return ResourceManager.GetString("Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Word Wrap.
        /// </summary>
        public static string WordWrap {
            get {
                return ResourceManager.GetString("WordWrap", resourceCulture);
            }
        }
    }
}
