blank_issues_enabled: true
contact_links:
  - name: Issue with ASP.NET Core
    url:  https://github.com/dotnet/aspnetcore/issues/new/choose
    about: Please open issues relating to ASP.NET Core in dotnet/aspnetcore.
  - name: Issue with .NET SDK
    url:  https://github.com/dotnet/sdk/issues/new/choose
    about: Please open issues relating to the .NET SDK itself in dotnet/sdk.
