//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PssdiagConfig {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PssdiagConfig.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectBlocking.
        /// </summary>
        internal static string CollectBlocking {
            get {
                return ResourceManager.GetString("CollectBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectProfiler.
        /// </summary>
        internal static string CollectBlockingMaxFileSize {
            get {
                return ResourceManager.GetString("CollectBlockingMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectBlockingShutdown.
        /// </summary>
        internal static string CollectBlockingShutdown {
            get {
                return ResourceManager.GetString("CollectBlockingShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectBlockingStartup.
        /// </summary>
        internal static string CollectBlockingStartup {
            get {
                return ResourceManager.GetString("CollectBlockingStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectEventLogs.
        /// </summary>
        internal static string CollectEventLogs {
            get {
                return ResourceManager.GetString("CollectEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectEventLogsShutdown.
        /// </summary>
        internal static string CollectEventLogShutdown {
            get {
                return ResourceManager.GetString("CollectEventLogShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectEventLogsStartup.
        /// </summary>
        internal static string CollectEventLogsStartup {
            get {
                return ResourceManager.GetString("CollectEventLogsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectPerfmon.
        /// </summary>
        internal static string CollectPerfmon {
            get {
                return ResourceManager.GetString("CollectPerfmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectPerfmonShutdown.
        /// </summary>
        internal static string CollectPerfmonShutdown {
            get {
                return ResourceManager.GetString("CollectPerfmonShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectProfiler.
        /// </summary>
        internal static string CollectProfiler {
            get {
                return ResourceManager.GetString("CollectProfiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectSqldiagStartup.
        /// </summary>
        internal static string CollectSqldiag {
            get {
                return ResourceManager.GetString("CollectSqldiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectSqldiagShutdown.
        /// </summary>
        internal static string CollectSqldiagShutdown {
            get {
                return ResourceManager.GetString("CollectSqldiagShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectSqldiagStartup.
        /// </summary>
        internal static string CollectSqldiagStartup {
            get {
                return ResourceManager.GetString("CollectSqldiagStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CollectXEvent.
        /// </summary>
        internal static string CollectXEvent {
            get {
                return ResourceManager.GetString("CollectXEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Feature.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný InstanceName.
        /// </summary>
        internal static string InstanceName {
            get {
                return ResourceManager.GetString("InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MachineName.
        /// </summary>
        internal static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OutputFolder.
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PerfmonInterval.
        /// </summary>
        internal static string PerfmonInterval {
            get {
                return ResourceManager.GetString("PerfmonInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PerfmonMaxFileSize.
        /// </summary>
        internal static string PerfmonMaxFileSize {
            get {
                return ResourceManager.GetString("PerfmonMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Platform.
        /// </summary>
        internal static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ProfilerFileCount.
        /// </summary>
        internal static string ProfilerFileCount {
            get {
                return ResourceManager.GetString("ProfilerFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ProfilerMaxFileSize.
        /// </summary>
        internal static string ProfilerMaxFileSize {
            get {
                return ResourceManager.GetString("ProfilerMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XEventFileCount.
        /// </summary>
        internal static string XEventFileCount {
            get {
                return ResourceManager.GetString("XEventFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XEventMaxFileSize.
        /// </summary>
        internal static string XEventMaxFileSize {
            get {
                return ResourceManager.GetString("XEventMaxFileSize", resourceCulture);
            }
        }
    }
}
