//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PssdiagConfig {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PssdiagConfig.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;DiagMgr&gt;
        ///  &lt;Versions&gt;
        ///    &lt;Version name=&quot;9&quot;  /&gt;
        ///    &lt;Version name=&quot;10&quot;  /&gt;
        ///    &lt;Version name=&quot;11&quot;  /&gt;
        ///    &lt;Version name=&quot;12&quot;  /&gt;
        ///    &lt;Version name=&quot;13&quot;  /&gt;
        ///  &lt;/Versions&gt;
        ///  &lt;Features&gt;
        ///
        ///    &lt;Feature name=&quot;SQL&quot; enabled=&quot;true&quot;/&gt;
        ///  &lt;/Features&gt;
        ///  
        ///  &lt;Scenarios&gt;
        ///     &lt;DiagTemplate name=&quot;GeneralPerf&quot; friendlyname=&quot;General Performance&quot; target=&quot;file&quot;  DefaultChecked=&quot;false&quot;&gt;
        ///              &lt;Features&gt;
        ///               &lt;Feature name=&quot;SQL&quot; enabled=&quot;true&quot;/&gt; 
        ///               
        ///              &lt;/Features&gt;
        ///              &lt;Scenario [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string AllEvents {
            get {
                return ResourceManager.GetString("AllEvents", resourceCulture);
            }
        }
    }
}
